### PR TITLE
exercise 3

### PR DESCRIPTION
**Pull request by quinqu**
@wadells

### CODE REVIEW

**Comment by quinqu** [comment]
My comments in this PR are wrong. I just ran again and it seems like the loop is more efficient in terms of time. But in terms of space complexity the first is more efficient

**Review by wadells — COMMENTED** [review]
How did you test this? Without a large number of arguments, I'm not sure there would be a meaningful & reproducible difference between the two measurements.  Can you provide sample test configs & output?

**Comment by quinqu** [comment]
## Test 1: 

`go run exercise3.go "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123" "123"`

## Output 1: 

```
0.000009034s elapsed
0.000032581s elapsed
```

## Test 2: 

`go run exercise3.go "hello" "world"`

## Output 2: 

``` 
0.000001825s elapsed
0.000002617s elapsed
```
Not much of a difference with little input, but still the 2nd takes longer

**Comment by wadells** [comment]
Thanks! 

> 0.000009034s elapsed
> 0.000032581s elapsed

These numbers are reasonable enough.  I would encourage you to try an bigger N because N < 30 is pretty small from a big-O perspective.

Related food for thought:
https://gist.github.com/jboner/2841832

Questions:

1) Where do your observed runtimes fall in the above chart?

2) How large does N need to be such that your data would no longer fit into your cpu's cache? You can find cache size with `cat /proc/cpuinfo | grep -i cache`

3) How could you refactor to easily test the performance of the two approaches with large N (e.g 1000, or 1000000)?  That many cli arguments seems unwieldy and may hit some limit in the shell or exec about how many args can be passed.

We can meet to discuss these once you've thought about them or carry on the discussion here.

**Pull request merged**
